# Generated by Django 3.2.2 on 2021-07-08 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100, verbose_name='敏感词')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 13, 47, 53, 964818), verbose_name='用户创建时间'),
        ),
    ]
