# Generated by Django 3.2.2 on 2021-07-08 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitoring', '0002_auto_20210708_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('assets', models.CharField(max_length=100, verbose_name='资产')),
            ],
            options={
                'verbose_name': '监管单位',
                'verbose_name_plural': '监管单位',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 14, 46, 57, 222818), verbose_name='用户创建时间'),
        ),
    ]
