# Generated by Django 3.2.2 on 2021-07-12 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitoring', '0003_auto_20210708_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=200, verbose_name='任务名称')),
                ('tasktime', models.CharField(max_length=200, verbose_name='任务时间')),
                ('taskstatus', models.CharField(max_length=200, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.AddField(
            model_name='detictionlist',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 10, 22, 59, 482204), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='detictionlist',
            name='ip',
            field=models.CharField(default='', max_length=200, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='riskurl',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 10, 22, 59, 482204), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='riskurl',
            name='ip',
            field=models.CharField(default='', max_length=200, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='riskurl',
            name='keywords',
            field=models.CharField(default='', max_length=100, verbose_name='敏感词'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 10, 22, 59, 481204), verbose_name='用户创建时间'),
        ),
    ]
