# Generated by Django 3.2.2 on 2021-07-13 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitoring', '0004_auto_20210712_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskfinshtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 12, 51, 780000), verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='detictionlist',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 12, 51, 779000), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='riskurl',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 12, 51, 779000), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 12, 51, 780000), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 14, 12, 51, 778000), verbose_name='用户创建时间'),
        ),
    ]
